version: '3.8'

services:
  nonebot:
    build: .
    image: ghcr.io/misaka10843/murasame-bot:latest
    container_name: discord_bot
    restart: always
    ports:
      - "8989:8989"
    volumes:
      - ./.env.prod:/app/.env.prod:ro
    extra_hosts:
      # 允许容器访问宿主机网络 (Linux下有时需要)
      - "host.docker.internal:host-gateway"